import areaparticle from "./areaparticle";
import buy from "./buy";
import buybase from "./buybase";
import cleardp from "./cleardp";
import fill from "./fill";
import gamerule from "./gamerule";
import getdp from "./getdp";
import message from "./message";
import messageop from "./messageop";
import registertptarget from "./registertptarget";
import sell from "./sell";
import setdp from "./setdp";
import setlocation from "./setlocation";
import setparticle from "./setparticle";
import testparams from "./testparams";
export default () => {
    console.log("set commands");
    areaparticle();
    buy();
    buybase();
    cleardp();
    fill();
    gamerule();
    getdp();
    message();
    messageop();
    registertptarget();
    sell();
    setdp();
    setparticle();
    setlocation();
    testparams();
};
