import { Logger } from '../utils/logger';
import buy from './buy';
import buybase from './buybase';
import buyenchantedbook from './buyenchantedbook';
import cleardp from './cleardp';
import dice from './dice';
import fill from './fill';
import fixarea from './fixarea';
import gamerule from './gamerule';
import getdp from './getdp';
import message from './message';
import messageop from './messageop';
import migrate from './migrate';
import pray from './pray';
import registertptarget from './registertptarget';
import releasearea from './releasearea';
import renamedp from './renamedp';
import sell from './sell';
import setdp from './setdp';
import setsafezone from './setsafezone';
import showgamerules from './showgamerules';
import tp from './tp';
import transfer from './transfer';
import withdraw from './withdraw';
export default () => {
    Logger.log('set commands');
    buy();
    buybase();
    buyenchantedbook();
    cleardp();
    dice();
    fill();
    fixarea();
    gamerule();
    getdp();
    migrate();
    message();
    messageop();
    pray();
    registertptarget();
    releasearea();
    renamedp();
    sell();
    setdp();
    setsafezone();
    showgamerules();
    tp();
    transfer();
    withdraw();
};
